<link href="http://img1.cache.netease.com/cnews/img/gallery11/nph_gallery_2.11.css" rel="stylesheet" type="text/css" />
<style type="text/css">
#gallery47320 .nph_photo_view{ height:580px; }
#gallery47320 .nph_stream, #gallery47320 .nph_search{ height:780px;}
*html .nph_photo_view .infoPreviewBottom { bottom :0!important; }
</style>
<div class="nph_gallery nph_skin_white" id="gallery47320">
<div class="nph_bg">
<div class="nph_cnt clearfix">
<div class="nph_search_panel">
<form id="searchPhoto47320">
<span class="nph_search_input">
<label for="searchInput47320">搜索图片</label>
<input title="输入图片关键词" autocomplete="off" name="q" id="searchInput47320" />
</span>
<span class="nph_search_btn">
<button type="submit"></button>
</span>
</form>
</div>
<div class="nph_set_info">
<div id="setInfo47320">
<div class="nph_set_title">
<h2><a href="http://lady.163.com/photoview/0BSC0026/47320.html">可爱乖宝贝俊俊</a></h2><span class="nph_set_cur hidden" id="photoType47320">（<span id="photoIndex47320" class="nph_c_lh"></span>/9）</span><span class="nph_set_size" id="streamType47320">（共<span class="nph_c_lh">9</span>张）</span></div>
<p></p>
</div>
<div id="searchTheme47320" class="hidden">
<a href="" class="nph_btn_return" id="viewPhoto47320">< 返回</a>
<h3 class="hidden">找到<span></span>相关图片<span class="nph_search_count">（共<span class="nph_c_lh"></span>张）</span></h3>
<h3 class="hidden">未找到<span></span>相关图片</h3>
</div>
</div>
</div>
<span class="nph_hr_solid"></span>
<div id="modePhoto47320" class="nph_photo">
<div class="nph_photo_view">
<div class="nph_cnt" id="photoView47320"><i></i><img src="http://img1.cache.netease.com/cnews/img/gallery11/bg06.png" id="photo47320" /></div>
<div class="nph_photo_prev"><a href="#" hidefocus="true" class="nph_btn_pphoto" id="photoPrev47320" target="_self"></a></div>
<div class="nph_photo_next"><a href="#" hidefocus="true" class="nph_btn_nphoto" id="photoNext47320" target="_self"></a></div>
<div class="nph_photo_loading" id="photoLoading47320"></div>
</div>
<div class="nph_cnt">
<div class="nph_photo_ctrl">
<ul><li><a href="" class="nph_icon_orig" id="viewOrig47320">查看原图</a>|</li><li><a href="#q=1" class="nph_icon_stream" id="viewStream47320">全部图片</a>|</li></ul>
</div>
<div class="nph_photo_desc" id="photoDesc47320"></div>
</div>
<span class="nph_hr_solid"></span>
<div class="nph_cnt clearfix">
<div class="nph_photo_thumb" id="scrl47320">
<div class="clearfix">
<div class="nph_scrl">
<div class="nph_scrl_thumb">
<div class="nph_scrl_main">
<ul class="nph_list_thumb" id="thumb47320"></ul>
</div>
<div class="nph_scrl_bar clearfix">
<span class="nph_scrl_lt"></span>
<span class="nph_scrl_rt"></span>
<div class="nph_scrl_bd">
<div class="nph_scrl_ct">
<a href="" hidefocus="true" class="nph_btn_scrl" id="bar47320">
<b class="nph_btn_lt"></b>
<b class="nph_btn_rt"></b>
<span class="nph_btn_bd"><span><b class="nph_btn_ct"></b></span></span>
</a>
</div>
</div>
</div>
</div>
</div>
<span class="nph_scrl_prev"><a href="" hidefocus="true" class="nph_btn_pscrl" id="scrlPrev47320"></a></span>
<span class="nph_scrl_next"><a href="" hidefocus="true" class="nph_btn_nscrl" id="scrlNext47320"></a></span>
</div>
</div>
</div>
</div>
<div id="modeStream47320" class="nph_stream hidden">
<div class="nph_cnt">
<div class="nph_stream_view" id="stream47320"></div>
</div>
</div>
<div id="modeSearch47320" class="nph_search hidden">
<div class="nph_cnt">
<div class="nph_search_view" id="search47320"></div>
</div>
</div>
<textarea class="hidden" id="photoList47320">
<li>
<a href="#p=93TP7V5I0BSC0026" hidefocus="true"><img src="http://img3.cache.netease.com/photo/0026/2013-07-16/s_93TP7V5I0BSC0026.jpg" alt="【昵称：俊俊 性别：男】【生日：2012-12-08 】【所在地区：广东-东莞市】" /></a>
<h2>【昵称：俊俊 性别：男】【生日：2012-12-08 】【所在地区：广东-东莞市】</h2>
<p></p>
<i title="img">http://img3.cache.netease.com/photo/0026/2013-07-16/93TP7V5I0BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP7V5I0BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP7VJL0BSC0026" hidefocus="true"><img src="http://img3.cache.netease.com/photo/0026/2013-07-16/s_93TP7VJL0BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>宝贝5个月的时候，爸爸妈妈给拍了写真，是不是很可爱呀</p>
<i title="img">http://img3.cache.netease.com/photo/0026/2013-07-16/93TP7VJL0BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP7VJL0BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP80A30BSC0026" hidefocus="true"><img src="http://img4.cache.netease.com/photo/0026/2013-07-16/s_93TP80A30BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>我是乖宝宝，看我的表情多吧</p>
<i title="img">http://img4.cache.netease.com/photo/0026/2013-07-16/93TP80A30BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP80A30BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP80G70BSC0026" hidefocus="true"><img src="http://img3.cache.netease.com/photo/0026/2013-07-16/s_93TP80G70BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>嘻嘻，小红军来啦</p>
<i title="img">http://img4.cache.netease.com/photo/0026/2013-07-16/93TP80G70BSC0026.jpg</i>
<i title="timg">http://img3.cache.netease.com/photo/0026/2013-07-16/t_93TP80G70BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP7VMD0BSC0026" hidefocus="true"><img src="http://img3.cache.netease.com/photo/0026/2013-07-16/s_93TP7VMD0BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>看我多会吃手手，手手真好吃呀</p>
<i title="img">http://img4.cache.netease.com/photo/0026/2013-07-16/93TP7VMD0BSC0026.jpg</i>
<i title="timg">http://img3.cache.netease.com/photo/0026/2013-07-16/t_93TP7VMD0BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP802E0BSC0026" hidefocus="true"><img src="http://img4.cache.netease.com/photo/0026/2013-07-16/s_93TP802E0BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>我是乖乖的小奶牛</p>
<i title="img">http://img3.cache.netease.com/photo/0026/2013-07-16/93TP802E0BSC0026.jpg</i>
<i title="timg">http://img3.cache.netease.com/photo/0026/2013-07-16/t_93TP802E0BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP7VE70BSC0026" hidefocus="true"><img src="http://img3.cache.netease.com/photo/0026/2013-07-16/s_93TP7VE70BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>宝贝在等妈妈下班，长个大眼睛望呀望，妈妈什么时候回来呢</p>
<i title="img">http://img4.cache.netease.com/photo/0026/2013-07-16/93TP7VE70BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP7VE70BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP7VUI0BSC0026" hidefocus="true"><img src="http://img4.cache.netease.com/photo/0026/2013-07-16/s_93TP7VUI0BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>宝贝7个月啦，哈哈，最喜欢洗澡啦，看看坐在澡盆里多开心，开心的大眼睛都睁大啦</p>
<i title="img">http://img3.cache.netease.com/photo/0026/2013-07-16/93TP7VUI0BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP7VUI0BSC0026.jpg</i>
</li>
<li>
<a href="#p=93TP807V0BSC0026" hidefocus="true"><img src="http://img4.cache.netease.com/photo/0026/2013-07-16/s_93TP807V0BSC0026.jpg" alt="" /></a>
<h2></h2>
<p>爸爸带我打预防针啦，我很坚强，我不哭，但是好像看其他小朋友都哭了</p>
<i title="img">http://img3.cache.netease.com/photo/0026/2013-07-16/93TP807V0BSC0026.jpg</i>
<i title="timg">http://img4.cache.netease.com/photo/0026/2013-07-16/t_93TP807V0BSC0026.jpg</i>
</li>
</textarea>
<div id="galleryTpl47320" class="hidden">
<div title="stream">
<!--
<ul class="nph_list_stream">
<#
for(var i = 0, len = stream.length; i < len; i++){
#>
<li>
<div><a href="#p=<#=stream[i].id#>"><i></i><img src="<#=stream[i].timg#>" /></a></div>
<h3><a href="#p=<#=stream[i].id#>" title="<#=stream[i].title#>"><#=stream[i].title.slice(0,26)#></a></h3>
</li>
<#
}
#>
</ul>
<div class="nph_pages">
<#
if(page <= 1){
#>
<span class="nph_pages_turn">上一页</span>
<#
} else {
#>
<a href="#q=<#=page-1#>" class="nph_pages_turn">上一页</a>
<#
}
var before = true, behind = true;
for(var i = 1, len = total; i <= len; i++){
if((page <= 5 && i <= 7) || (page > 5 && page <= len - 5 && i > page - 3 && i < page + 3) || (page > len - 5 && i > len - 7) || i == 1 || i == len){
if(page == i){
#>
<span class="nph_pages_active"><#=i#></span>
<#
} else {
#>
<a href="#q=<#=i#>"><#=i#></a>
<#
}
} else {
if(before && i < page){
#>
……
<#
before = false;
}
if(behind && i > page){
#>
……
<#
behind = false;
}
}
}
if(page >= total){
#>
<span class="nph_pages_turn">下一页</span>
<#
} else {
#>
<a href="#q=<#=page+1#>" class="nph_pages_turn">下一页</a>
<#
}
#>
</div>
-->
</div>
<div title="search">
<!--
<ul class="nph_list_stream clearfix">
<#
for(var i = 0, len = stream.length; i < len; i++){
#>
<li>
<div><a href="<#=stream[i].pageurl#>"><i></i><img src="<#=stream[i].imgsrc#>" /></a></div>
<h3><a href="<#=stream[i].pageurl#>" title="<#=stream[i].title#>"><#=stream[i].title.slice(0, 13)#></a></h3>
<p><#=stream[i].ptime#></p>
</li>
<#
}
#>
</ul>
<div class="nph_pages clearfix">
<#
if(page <= 1){
#>
<span class="nph_pages_turn">上一页</span>
<#
} else {
#>
<a href="#s=<#=q#>&q=<#=page-1#>" class="nph_pages_turn">上一页</a>
<#
}
var before = true, behind = true;
for(var i = 1, len = total; i <= len; i++){
if((page <= 5 && i <= 7) || (page > 5 && page <= len - 5 && i > page - 3 && i < page + 3) || (page > len - 5 && i > len - 7) || i == 1 || i == len){
if(page == i){
#>
<span class="nph_pages_active"><#=i#></span>
<#
} else {
#>
<a href="#s=<#=q#>&q=<#=i#>"><#=i#></a>
<#
}
} else {
if(before && i < page){
#>
……
<#
before = false;
}
if(behind && i > page){
#>
……
<#
behind = false;
}
}
}
if(page >= total){
#>
<span class="nph_pages_turn">下一页</span>
<#
} else {
#>
<a href="#s=<#=q#>&q=<#=page+1#>" class="nph_pages_turn">下一页</a>
<#
}
#>
</div>
-->
</div>
</div>
</div>
</div>
<script type="text/javascript" language="javascript" src="http://img1.cache.netease.com/cnews/js/ntes_jslib_1.x.js" charset="gb2312"></script>
<script type="text/javascript" language="javascript" src="http://img1.cache.netease.com/cnews/js/ntes_jslib_ui_0.x.js" charset="gb2312"></script>
<script type="text/javascript" language="javascript" src="http://img1.cache.netease.com/cnews/img/gallery11/ntes_ui_scroll.js" charset="gb2312"></script>
<script type="text/javascript" language="javascript" src="http://img1.cache.netease.com/cnews/img/gallery11/nph_gallery_2.11.js" charset="gb2312"></script>
<script type="text/javascript">
  NTES.ready(function ($) { new nph.Gallery({ sn: "47320" }); });
  </script>
<img src="http://img2.cache.netease.com/nocache/statistic/mod003.gif" width="0" height="0" border="0" />      