
<script type="text/javascript" language="javascript">//<![CDATA[
var isShowComments = true,tieChannel = "sports",isStrict = true;
//]]></script>
<!--tie begin-->
<link type="text/css" charset="utf-8" rel="stylesheet" href="http://img1.cache.netease.com/utf8/tie/tieanywhere2.2.9-min.css">
<div id="tieArea" class="tie-area">
    <div class="tie-show js-tie-show">
        <div class="tie-titlebar">
            <strong></strong><span class="tie-info">
            <a href="#" class="js-actCount tie-actCount" target="_blank">0</a>人跟贴 <span class="info-line">|</span> 
            <a href="#" class="js-joinCount tie-actCount" target="_blank">0</a>人参与 </span>
        </div>
        <div class="js-tie-data">
        </div>
    </div>
    <div class="tie-post js-post-area" id="tiePostBox" >
        <div class="tie-titlebar tie-title-mend">
            <strong>网友跟贴</strong> 
            <span class="tie-info"><a href="#" class="js-bactCount tie-actCount" target="_blank">0</a>人跟贴 <span class="info-line">|</span> 
            <a href="#" class="js-bjoinCount tie-actCount" target="_blank">0</a>人参与 <span class="info-line">|</span>
                <a href="http://m.163.com/newsapp/" target="_blank" class="tie-byMobile"><em class="tie-sprite"></em>
                    手机发跟贴</a> <span class="info-line">|</span> <a href="#" class="tie-reg js-reg" target="_blank">注册</a>
            </span>
        </div>
        <style type="text/css">
    .tie-post .tie-post-area .post-area-photo{border-left-color:#cc1b1b;border-bottom-color:#cc1b1b;}
    .tie-post .tie-post-area .post-area-input{ border-right-color:#cc1b1b;border-bottom-color:#cc1b1b;}
    #tieAds{ border:1px solid #cc1b1b;border-bottom-width:0;width:588px; overflow:hidden; }
    .tie-post .tie-post-area .post-area-hover { border-color:#aad2ff;}
</style>
<div style="text-align:center;" id="tieAds">
<a href="http://g.163.com/a?CID=21960&Values=2760452807&Redirect=http://idigger.allyes.com/main/c?db=idigger&bid=59638,28853,1&cid=26723,21327,364&sid=58998&show=ignore&url=http://idigger.allyes.com/main/c?db=mso&bid=159508,79794,6135&cid=82790,6654,149&sid=159605&show=ignore&url=http://www.wlj-china.com/delicacy2013/" target="_blank"><img src="http://img1.126.net/channel7/014430/jdb59038_130715.jpg" width="590" height="38"></a>
</div>        <div class="tie-postform">
            <form target="_blank" method="post" action="http://comment.house.163.com/reply/dopost.jsp"
            class="js-postForm">
            <div class="tie-post-area">
                 <div class="post-area-photo js-ularea-photo">
                    <a href="javascript:;" target="_self" title="请登录"  class="tie-sprite area-photo-nohover">
                    </a>
                </div>
                <div class="post-area-photo js-area-photo" style="display: none;">
                    <a href="http://tie.163.com/setting/avatar/?from=userPanel" title="请上传头像" class="tie-sprite area-photo-icon">
                    </a>
                </div>
                <div class="post-area-photo js-larea-photo" style="display: none;">
                    <a href="http://tie.163.com/setting/avatar/?from=userPanel">
                        <img width="65" height="65" />
                    </a>
                </div>
                <div class="post-area-input js-postinput">
                    <textarea rows="8" cols="80" class="tie-textarea js-postBox" name="body"></textarea>
                    <div class="area-input-tips js-tie-tips">
                        文明上网，登录发贴</div>
                    <div class="area-input-leftline">
                    </div>
                    <div class="area-input-topline">
                    </div>
                    <input type="hidden" name="board" value="" />
                    <input type="hidden" name="username" />
                    <input type="hidden" name="threadid" value="" />
                    <input type="hidden" name="url" value="http://comment.house.163.com/bj_house_bbs/8IBKMI6B00073SD3.html" />
                    <input type="hidden" name="isTinyBlogSyn" value="1" />
                </div>
            </div>
            </form>
            <div class="tie-author js-tie-author">
                <div class="js-unlogin">
                    <div class="js-loginInput">
                        <div class="author-name">
                            <em class="tie-sprite"></em>
                            <input type="text" class="tie-textbox js-username" />
                            <div class="author-tips js-nametips">
                                账号</div>
                        </div>
                        <div class="author-pwd">
                            <em class="tie-sprite"></em>
                            <input type="password" class="tie-textbox js-password" />
                            <div class="author-tips js-pwdtips">
                                密码</div>
                        </div>
                    </div>
                    <div class="tie-author-login">
                        <label>
                            <input type="checkbox" checked="checked" class="js-save" />自动登录</label>
                        <label class="js-syn">
                            <input type="checkbox" checked="checked" /><em class="tie-sprite"></em></label>
                        <a href="javascript:void(0);" target="_self" class="tie-sprite post-btn js-loginPostBtn">
                            登录并发表</a>
                    </div>
                </div>
                <div class="js-login" style="display: none">
                    <div class="tie-author-logon">
                        <a rel="nofollow" target="_blank" class="js-tie-myhome" href="http://tie.163.com/reply/myaction.jsp">
                            <strong class="js-tie-username"></strong></a>&nbsp; <a rel="nofollow" class="js-tie-myposts"
                                target="_blank" href="http://tie.163.com/reply/myaction.jsp">我的跟贴</a> |
                        <a rel="nofollow" target="_blank" href="http://t.163.com/">我的微博</a> | <a rel="nofollow"
                            class="js-tie-logout" href="http://reg.163.com/Logout.jsp" target="_self">退出</a>
                    </div>
                    <div class="tie-author-login">
                        <label class="js-syn">
                            <input type="checkbox" checked="checked"  /><em class="tie-sprite"></em></label>
                        <a href="javascript:void(0);" target="_self" class="tie-sprite post-btn js-postBtn">
                            马上发表</a>
                    </div>
                </div>
            </div>
        </div>
        <p class="tie-reminder">
            网友评论仅供其表达个人看法，并不表明网易立场。</p>
    </div>
</div>
<script charset="utf-8" src="http://img1.cache.netease.com/utf8/loader/loader1.0.3.js "  language="javascript" type="text/javascript"></script>
        
                                        <script type="text/javascript">
    if (typeof isForceShowComment != "undefined") {
        isShowComments = isForceShowComment;
    };
    function tieInit() {
        tie_load({
            urs: "http://img1.cache.netease.com/utf8/microblog/urs/urs1.0.3.js",
            tie: "http://img1.cache.netease.com/utf8/tie/tieanywhere2.6.0-min.js"
        },
            function() {
                var replyCount = 20,
                    totalCount = 50,
                    threadId = "93VI8G1P00051CDG",
                    boardId = "sports_zh_bbs",
                    host = tieChannel;
                $(".js-tielink").attr("href", "http://comment." + host + ".163.com/" + boardId + "/" + threadId + ".html")
                $(".js-tiecount").attr("innerHTML", totalCount);
                $(".js-joinCount").attr("innerHTML", TieAnywhere.formatNumber(totalCount.toString(), 3));
                $(".js-bjoinCount").attr("innerHTML", TieAnywhere.formatNumber(totalCount.toString(), 3));
                $(".js-actCount").attr("innerHTML", TieAnywhere.formatNumber(replyCount.toString(), 3));
                $(".js-bactCount").attr("innerHTML", TieAnywhere.formatNumber(replyCount.toString(), 3));
                new TieAnywhere.Tie({
                    wraper: NTES("#tieArea"),
                    threadId: threadId,
                    boardId: boardId,
                    host: host,
                    isShowComment: isShowComments,
                    isStrict: isStrict
                });
            })
    };
    tie_ready(function() {
        if (!window.NTES) {
            tie_load({ lib: "http://img1.cache.netease.com/cnews/js/ntes_jslib_1.x.js" }, function() {
                tieInit();
            }, "GBK")
        } else {
            tieInit();
        };
    });
</script>
<!--tie end-->